"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isAndroidWithLocationCallSupport = exports.isIOSWithLocationCallSupport = exports.inBaidu = exports.inWeibo = exports.inQQ = exports.inWeixin = exports.enableApplink = exports.enableUniversalLink = exports.isAndroid = exports.isIos = void 0;
var detector_1 = require("./detector");
exports.isIos = detector_1.detector.os.name === 'ios';
exports.isAndroid = detector_1.detector.os.name === 'android';
exports.enableUniversalLink = exports.isIos && detector_1.detector.os.version >= 9;
exports.enableApplink = exports.isAndroid && detector_1.detector.os.version >= 6;
exports.inWeixin = detector_1.detector.browser.name === 'micromessenger';
exports.inQQ = detector_1.detector.browser.name === 'qq';
exports.inWeibo = detector_1.detector.browser.name === 'weibo';
exports.inBaidu = detector_1.detector.browser.name === 'baidu';
exports.isIOSWithLocationCallSupport = exports.isIos && detector_1.detector.browser.name == 'safari' && detector_1.detector.os.version >= 9;
var isChromeWithLocationCallSupport = detector_1.detector.browser.name == 'chrome' && detector_1.detector.browser.version > 55;
var isSamsungWithLocationCallSupport = detector_1.detector.browser.name == 'samsung';
exports.isAndroidWithLocationCallSupport = exports.isAndroid && (isChromeWithLocationCallSupport || isSamsungWithLocationCallSupport);
